name: 'Telemetry'
on: pull_request
permissions: {}
jobs:
  check-metadata:
    name: 'Check metadata'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v5'
        with:
          persist-credentials: false

      - uses: 'actions/setup-node@v5'
        with:
          node-version: 'lts/*'

      - name: 'Run ProX-Code-telemetry-extractor'
        run: 'npx --package=@ProX-Code/telemetry-extractor@1.14.0 --yes ProX-Code-telemetry-extractor -s .'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
